=== csimon1/LOG530/infovis/data/tree/treeml.dtd
<!--
	Copyright (c) 2002
	Jean-Daniel Fekete, INRIA
	Catherine Plaisant, University of Maryland

	$Id: treeml.dtd,v 1.7 2003/03/26 12:22:11 fekete Exp $

	DTD describing a tree structure for visualization.

-->
<!ENTITY dcns 'http://purl.org/dc/elements/1.1/' >
<!ENTITY % dcnsdecl 'xmlns:dc CDATA #FIXED "&dcns;"' >

<!ELEMENT tree (metadata? ,declarations? ,(branch| leaf)* )>
<!ATTLIST tree
  version CDATA "1.0"
  src CDATA #IMPLIED
  desc CDATA #IMPLIED
  date CDATA #IMPLIED
  author CDATA #IMPLIED
  %dcnsdecl;
>

<!-- Metadata information -->
<!--
 see http://dublincore.org/documents/2002/09/09/dc-xml-guidelines/
 for full details on implementing Dublin Core in XML.

 Largely inspired from "Expressing Simple Dublin Core in RDF/XML"
 http://dublincore.org/documents/2002/07/31/dcmes-xml/dcmes-xml-dtd.dtd
-->


<!ENTITY % dcmes "dc:title | dc:creator | dc:subject | dc:description |
dc:publisher | dc:contributor | dc:date | dc:type | dc:format |
dc:identifier | dc:source | dc:language | dc:relation | dc:coverage |
dc:rights" >

<!-- The elements from DCMES 1.1 -->

<!-- The name given to the resource. -->
<!ELEMENT dc:title (#PCDATA)>
<!ATTLIST dc:title xml:lang CDATA #IMPLIED>

<!-- An entity primarily responsible for making the content of the
resource. -->
<!ELEMENT dc:creator (#PCDATA)>
<!ATTLIST dc:creator xml:lang CDATA #IMPLIED>

<!-- The topic of the content of the resource. -->
<!ELEMENT dc:subject (#PCDATA)>
<!ATTLIST dc:subject xml:lang CDATA #IMPLIED>

<!-- An account of the content of the resource. -->
<!ELEMENT dc:description (#PCDATA)>
<!ATTLIST dc:description xml:lang CDATA #IMPLIED>

<!-- The entity responsible for making the resource available. -->
<!ELEMENT dc:publisher (#PCDATA)>
<!ATTLIST dc:publisher xml:lang CDATA #IMPLIED>

<!-- An entity responsible for making contributions to the content of
the resource. -->
<!ELEMENT dc:contributor (#PCDATA)>
<!ATTLIST dc:contributor xml:lang CDATA #IMPLIED>

<!-- A date associated with an event in the life cycle of the resource. -->
<!ELEMENT dc:date (#PCDATA)>
<!ATTLIST dc:date xml:lang CDATA #IMPLIED>

<!-- The nature or genre of the content of the resource. -->
<!ELEMENT dc:type (#PCDATA)>
<!ATTLIST dc:type xml:lang CDATA #IMPLIED>

<!-- The physical or digital manifestation of the resource. -->
<!ELEMENT dc:format (#PCDATA)>
<!ATTLIST dc:format xml:lang CDATA #IMPLIED>

<!-- An unambiguous reference to the resource within a given context. -->
<!ELEMENT dc:identifier (#PCDATA)>
<!ATTLIST dc:identifier xml:lang CDATA #IMPLIED>

<!-- A Reference to a resource from which the present resource is derived. -->
<!ELEMENT dc:source (#PCDATA)>
<!ATTLIST dc:source xml:lang CDATA #IMPLIED>

<!-- A language of the intellectual content of the resource. -->
<!ELEMENT dc:language (#PCDATA)>
<!ATTLIST dc:language xml:lang CDATA #IMPLIED>

<!-- A reference to a related resource. -->
<!ELEMENT dc:relation (#PCDATA)>
<!ATTLIST dc:relation xml:lang CDATA #IMPLIED>

<!-- The extent or scope of the content of the resource. -->
<!ELEMENT dc:coverage (#PCDATA)>
<!ATTLIST dc:coverage xml:lang CDATA #IMPLIED>

<!-- Information about rights held in and over the resource. -->
<!ELEMENT dc:rights (#PCDATA)>
<!ATTLIST dc:rights xml:lang CDATA #IMPLIED>

<!-- All other information -->
<!ELEMENT metainfo (#PCDATA)>
<!ATTLIST metainfo
        name CDATA #REQUIRED
        type CDATA #IMPLIED
        xml:lang CDATA #IMPLIED>

<!ELEMENT metadata ( %dcmes; | metainfo )* >

<!ELEMENT declarations (attributeDecl+) >
<!ELEMENT attributeDecl (#PCDATA | metadata)* >
<!ATTLIST attributeDecl
  name CDATA #REQUIRED
  type (Int|Integer|Long|Float|Real|String|Date|Category) "Int"
  control CDATA #IMPLIED >

<!ELEMENT branch ( attribute*, (branch | leaf)* ) >
<!ATTLIST branch
  label CDATA #IMPLIED
  degree CDATA #IMPLIED>

<!ELEMENT leaf (attribute*) >
<!ATTLIST leaf
  label CDATA #IMPLIED >

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
  name CDATA #REQUIRED
  value CDATA #REQUIRED >

=== csimon1/LOG530/Lab1/infovis/data/tree/tree3.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE tree SYSTEM "treeml.dtd">
<tree>
 <metadata>
  <dc:title>Example of tree from the article "A Node-Positioning Algorithm"</dc:title>
 </metadata>
 <declarations>
  <attributeDecl name="name" type="String"/>
 </declarations>
 <branch>
  <attribute name="name" value="O"/>
  <leaf>
   <attribute name="name" value="A"/>
  </leaf>
  <leaf>
   <attribute name="name" value="B"/>
  </leaf>
  <leaf>
   <attribute name="name" value="C"/>
  </leaf>  
 </branch>
</tree>

=== csimon1/LOG530/infovis/data/tree/nodelinktest.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE tree SYSTEM "treeml.dtd">
<tree>
 <metadata>
  <dc:title>Example of tree from the article "A Node-Positioning Algorithm"</dc:title>
 </metadata>
 <declarations>
  <attributeDecl name="name" type="String"/>
  <attributeDecl name="weight" type="Integer"/>
 </declarations>
 <branch>
  <attribute name="name" value="O"/>
  <attribute name="weight" value="1"/>
  <branch>
   <attribute name="name" value="E"/>
  <attribute name="weight" value="2"/>
   <leaf>
    <attribute name="name" value="A"/>
    <attribute name="weight" value="3"/>
   </leaf>
   <branch>
    <attribute name="name" value="D"/>
    <attribute name="weight" value="4"/>
    <leaf>
     <attribute name="name" value="B"/>
     <attribute name="weight" value="5"/>
    </leaf>
    <leaf>
     <attribute name="name" value="C"/>
     <attribute name="weight" value="6"/>
    </leaf>    
   </branch>
  </branch>
  <leaf>
   <attribute name="name" value="F"/>
   <attribute name="weight" value="7"/>
  </leaf>
  <branch>
   <attribute name="name" value="N"/>
   <attribute name="weight" value="8"/>
   <branch>
    <attribute name="name" value="G"/>
    <attribute name="weight" value="9"/>
    <leaf>
     <attribute name="name" value="H"/>
     <attribute name="weight" value="10"/>
    </leaf>
    <leaf>
     <attribute name="name" value="I"/>
     <attribute name="weight" value="11"/>
    </leaf>
    <leaf>
     <attribute name="name" value="J"/>
     <attribute name="weight" value="12"/>
    </leaf>
    <leaf>
     <attribute name="name" value="K"/>
     <attribute name="weight" value="13"/>
    </leaf>
    <leaf>
     <attribute name="name" value="L"/>
     <attribute name="weight" value="14"/>
    </leaf>
   </branch>
   <leaf>
    <attribute name="name" value="M"/>
    <attribute name="weight" value="15"/>
   </leaf>
  </branch>
 </branch>
</tree>
